name: Atualizar planilha

on:
  workflow_dispatch:
  schedule:
    - cron: '7 16 * * *'   # 13:07 BRT
    - cron: '23 17 * * *'  # 14:23 BRT
    - cron: '41 18 * * *'  # 15:41 BRT

jobs:
  atualizar:
    runs-on: ubuntu-latest

    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Executar script
        run: python atualiza_planilha.py
