name: Atualizar planilha

on:
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Executar script
        run: python atualiza_planilha.py
